trigger:
- master
    
pool:
  vmImage: "ubuntu-latest"

steps:
- task: UseDotNet@2
  inputs:
    version: "5.0.x"
    includePreviewVersions: true

- script: dotnet publish -c Release FeedReader.sln

- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'FeedReader.WebClient'
    pathToPublish: 'WebClient/bin/Release/netstandard2.1/publish/wwwroot'
