trigger:
  - master
      
pool:
  vmImage: "windows-2019"

steps:
- checkout: self
  submodules: true

- task: UseDotNet@2
  displayName: Install DotNet 5.0.x
  inputs:
    version: "5.0.x"
    performMultiLevelLookup: true
    includePreviewVersions: true

- task: UseDotNet@2
  displayName: Install DotNet 3.1.x
  inputs:
    version: "3.1.x"
    performMultiLevelLookup: true

- task: DotNetCoreCLI@2
  displayName: DotNet Restore
  inputs:
    command: restore
    includeNuGetOrg: true

- script: dotnet publish -c Release --no-restore
  displayName: Build

- task: PublishBuildArtifacts@1
  displayName: Publish WebClient
  inputs:
    artifactName: 'FeedReader.WebClient'
    pathToPublish: 'WebClient/bin/Release/net5.0/browser-wasm/publish/wwwroot'
  