trigger:
  - master
      
pool:
  vmImage: "windows-2019"

steps:
- task: UseDotNet@2
  inputs:
    version: "3.1.x"

- task: DotNetCoreCLI@2
  displayName: dotnet restore
  inputs:
    command: restore
    includeNuGetOrg: true

- script: dotnet publish -c Release --no-restore
  displayName: dontnet publush

- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'FeedReader.WebClient'
    pathToPublish: 'WebClient/bin/Release/netstandard2.1/publish/wwwroot'
  