version: '3.4'

services:
  feedreader.server:
    image: ${DOCKER_REGISTRY-}feedreaderserver
    build:
      context: .
      dockerfile: FeedReader.Server/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - AzureStorage=AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;DefaultEndpointsProtocol=http;BlobEndpoint=http://host.docker.internal:10000/devstoreaccount1;QueueEndpoint=http://host.docker.internal:10001/devstoreaccount1;TableEndpoint=http://host.docker.internal:10002/devstoreaccount1
      - JwtSecret=feedreader.org.local.test.signing.key
      - GitHubClientId=9b946fa144483d9ea46c
      - GitHubClientSecret=2f318350656e1f6682417de27d5ae677009a336f
    ports:
      - 80:80

  feedreader.taskserver:
    image: ${DOCKER_REGISTRY-}feedreadertaskserver
    build:
      context: .
      dockerfile: FeedReader.TaskServer/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AzureStorage=AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;DefaultEndpointsProtocol=http;BlobEndpoint=http://host.docker.internal:10000/devstoreaccount1;QueueEndpoint=http://host.docker.internal:10001/devstoreaccount1;TableEndpoint=http://host.docker.internal:10002/devstoreaccount1