name: Push On Master CI

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup DotNet Environment 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Setup DotNet Environment 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Restore
        shell: bash
        run: |
          dotnet restore

      - name: Build
        shell: bash
        run: |
          dotnet build -c Release --no-restore

      - name: Test
        shell: bash
        run: |
          dotnet test -c Release --no-build

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: feedreader.azurecr.io
          username: ${{ secrets.AZURECR_USERNAME }}
          password: ${{ secrets.AZURECR_PASSWORD }}

      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: FeedReader.Server/Dockerfile
          tags: feedreader.azurecr.io/feedreader-devtest:latest
          push: true

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: feedreader-webserver-westus2
          publish-profile: ${{ secrets.FEEDREADER_SERVER_PUBLISH_PROFILE }}
          images: justforfunclick/feedreader-devtest:latest
          slot-name: devtest
