name: Release CI

on:
  push:
    branches:
      - release

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup DotNet Environment 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Restore
        shell: bash
        run: |
          dotnet restore FeedReader.sln

      - name: Build
        shell: bash
        run: |
          dotnet build FeedReader.sln -c Release --no-restore

      - name: Test
        shell: bash
        run: |
          dotnet test FeedReader.sln -c Release --no-build

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: feedreader.azurecr.io
          username: ${{ secrets.AZURECR_USERNAME }}
          password: ${{ secrets.AZURECR_PASSWORD }}

      - name: Build FeedReader.Server docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: FeedReader.Server/Dockerfile
          tags: feedreader.azurecr.io/feedreader-webserver-release:latest
          push: true

      - name: Build FeedReader.TaskServer docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: FeedReader.TaskServer/Dockerfile
          tags: feedreader.azurecr.io/feedreader-taskserver-release:latest
          push: true